### PR TITLE
Support to configure request headers

### PR DESCRIPTION
**Pull request by jmvivo**
* Also fixed a problem which makes unusable for relative-url endpoints

### CODE REVIEW

**Comment by BenjaminVadant** [comment]
Hi,
really interesting.

Could you add info in the readme on how to use the new functionality ?

Once you've done that, I'll be happy to merge your pr.

**Comment by jmvivo** [comment]
Hi Benjamin,

This can be used in very same way than 'parameter' option. I already included it in readme file.

Do you think than it need more extended explication?

**Comment by BenjaminVadant** [comment]
It won't hurt to say it explicitely!

Thanks

**Comment by jmvivo** [comment]
Improved README

**Comment by jmvivo** [comment]
Hello!

Please, can you take a look about this?
Thanks!.

**Comment by BenjaminVadant** [comment]
Thank you @jmvivo

**Pull request merged**
